version: 2

build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10
  jobs:
    pre_build:
      - doit list
      - doit setup
      - doit list
      - doit lite
      - doit list

sphinx:
  builder: html
  configuration: docs/conf.py

conda:
  environment: docs/environment.yml
