dependencies:
  - firefox =115
  - geckodriver
  - pillow
  - robotframework-jupyterlibrary >=0.5.0
  - robotframework-pabot
  - robotframework-robocop
  - robotframework-tidy >=3.4.0
  - selenium <4.10.0
