dependencies:
  - firefox =102
  - geckodriver
  - conda-forge/label/robotframework_jupyterlibrary_alpha::robotframework-jupyterlibrary
    >=0.5.0a0
  - robotframework-pabot
  - robotframework-robocop
  - robotframework-tidy >=3.4.0
