dependencies:
  - ansi2html
  - autodoc-traits
  - docutils >=0.19
  - jupyterlite-core ==0.1.2
  - jupyterlite-core-with-libarchive
  - myst-nb
  - mdit-py-plugins <0.4.0
  - pydata-sphinx-theme
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
