dependencies:
  - ansi2html
  - autodoc-traits
  - docutils >=0.19
  - jupyterlite-core ==0.1.0
  - jupyterlite-core-with-libarchive
  - jupyterlite-pyodide-kernel ==0.0.6
  - myst-nb
  - pydata-sphinx-theme
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
