dependencies:
  - ansi2html
  - autodoc-traits
  - docutils >=0.19
  - doit
  - myst-nb
  - pkginfo
  - pydata-sphinx-theme
  - python-libarchive-c
  - sphinx
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
