dependencies:
  - importnb
  - ipydatagrid
  - ipylab >=0.7.0
  - lxml
  - networkx
  - pytest-asyncio
  - pytest-cov
  - pytest-github-actions-annotate-failures
  - pytest-html
  - pytest-json-report
  - pytest-xdist
  - scour
