_platforms:
  - linux-64

_inherit_from:
  - _build.yml
  - _build.yml
  - _channels.yml
  - _demo.yml
  - _doit.yml
  - _ext.yml
  - _lab/lab3.6.yml
  - _py/py3.11.yml
  - _run.yml

_target: ../../.binder/environment.yml

dependencies: []
