_platforms:
  - linux-64

_inherit_from:
  - _build.yml
  - _channels.yml
  - _docs.yml
  - _doit.yml
  - _ext.yml
  - _lab/lab3.6.yml
  - _py/py3.11.yml
  - _run.yml
  - _utest.yml

_target: ../../docs/environment.yml

dependencies: []
