#!/usr/bin/env python3

import os
import subprocess

os.environ.update(IN_BINDER="1")

subprocess.call(["doit", "-n4"])
subprocess.call(["doit", "list"])
subprocess.check_call(["doit"])

print(">>> OK")
