#!/usr/bin/env bash

# Copyright (c) 2023 ipyforcegraph contributors.
# Distributed under the terms of the Modified BSD License.

set -e

export IN_BINDER=1

source activate ${NB_PYTHON_PREFIX}

echo $@

exec jupyter-lab --collaborative --debug --expose-app-in-browser "${@:4}"
