name: Badges

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
      - name: Add Demo comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const PR_NUMBER = context.issue.number
            const { PR_HEAD_REF, PR_HEAD_USERREPO } = process.env;

            const RTD = `https://ipyforcegraph--${PR_NUMBER}.org.readthedocs.build/en/${PR_NUMBER}`;
            const BH = `https://mybinder.org/v2/gh/${PR_HEAD_USERREPO}/${PR_HEAD_REF}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: [
                'Try it on [![lite]][rtd] :arrow_left: ReadTheDocs or Binder :arrow_right: [![binder]][mb]',
                '[lite]: https://jupyterlite.rtfd.io/en/latest/_static/badge.svg',
                '[binder]: https://mybinder.org/badge_logo.svg',
                `[rtd]: ${RTD}/_static/lab/index.html?path=_index.ipynb`,
                `[mb]: ${BH}?urlpath=lab/tree/examples/_index.ipynb`
              ].join('\n')
            });
